const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const KEEP_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withAndroidKeepRawAssets.js - do not edit; android/ is regenerated by prebuild.

  Metro copies every non-drawable bundled asset (our .tflite models, .glb, .bin) into res/raw, and
  nothing in the compiled code references those resources by name: expo-asset opens them through
  Resources.getIdentifier(name, "raw", ...) at runtime. The AAPT2 resource shrinker cannot see a
  dynamic lookup, so with android.enableShrinkResourcesInReleaseBuilds=true (set in app.json via
  expo-build-properties) it is free to strip the models out of the release APK - which would leave
  the detector unable to load and the live green box unable to appear, with no build-time error.
-->
<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="@raw/*" />
`;

/**
 * Pin every res/raw asset against release resource shrinking.
 *
 * Applied in prebuild so it survives `expo prebuild --clean`.
 */
module.exports = function withAndroidKeepRawAssets(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        "app",
        "src",
        "main",
        "res",
        "raw",
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "keep.xml"), KEEP_XML);
      return config;
    },
  ]);
};
