import { t, useLocale } from '@/lib/i18n';
import { ThemedText } from "@/components/themed-text";
import { DocumentHeader } from "@/components/ui/document-header";
import { Icon } from "@/components/ui/icon";
import { Screen } from "@/components/ui/screen";
import { ContactLink } from "@/components/ui/settings-row";
import { router } from "expo-router";
import { ScrollView, StyleSheet, View } from "react-native";

import { Radius, Space } from "@/constants/theme";
import { useTheme } from "@/hooks/use-theme";

const LAST_UPDATED = "August 2026";
const CONTACT_EMAIL = "help.spoton@gmail.com";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  useLocale();
  return (
    <View style={styles.section}>
      <ThemedText type="title2" style={styles.sectionTitle}>
        {title}
      </ThemedText>
      {children}
    </View>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  useLocale();
  return (
    <ThemedText type="caption" themeColor="brand" style={styles.subHeading}>
      {children}
    </ThemedText>
  );
}

function Paragraph({ children }: { children: React.ReactNode }) {
  useLocale();
  return (
    <ThemedText type="subhead" style={styles.paragraph}>
      {children}
    </ThemedText>
  );
}

function Bullet({
  label,
  children,
}: {
  label?: string;
  children: React.ReactNode;
}) {
  useLocale();
  const theme = useTheme();
  return (
    <View style={styles.bulletRow}>
      <View style={[styles.bulletDot, { backgroundColor: theme.brand }]} />
      <ThemedText type="subhead" style={styles.bulletText}>
        {label ? (
          <ThemedText type="subhead" style={styles.bulletLabel}>
            {label}:{" "}
          </ThemedText>
        ) : null}
        {children}
      </ThemedText>
    </View>
  );
}

/** Inline tappable link to the Privacy Policy, for use inside body copy. */
function PolicyLink() {
  useLocale();
  return (
    <ThemedText
      type="subhead"
      themeColor="brand"
      style={styles.inlineLink}
      onPress={() => router.push("/profile/privacy")}
    >
      {t("Privacy Policy")}</ThemedText>
  );
}

function WarningBanner({ children }: { children: React.ReactNode }) {
  useLocale();
  const theme = useTheme();
  return (
    <View
      style={[
        styles.warningBanner,
        {
          backgroundColor: theme.riskCriticalBg,
          borderColor: theme.riskCritical,
        },
      ]}
    >
      <Icon
        name="exclamationmark.triangle.fill"
        tintColor={theme.riskCritical}
        size={20}
      />
      <ThemedText
        type="subhead"
        themeColor="riskCritical"
        style={styles.warningText}
      >
        {children}
      </ThemedText>
    </View>
  );
}

export default function TermsScreen() {
  useLocale();
  return (
    <Screen padded={false}>
      <DocumentHeader title={t("Terms and Conditions")} />

      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <ThemedText
          type="footnote"
          themeColor="textSecondary"
          style={styles.updated}
        >{t("Last Updated: ")}{t(LAST_UPDATED)}
        </ThemedText>

        <Section title={t("1. Acceptance of These Terms")}>
          <Paragraph>{t("By creating an account or using SpotOn, you acknowledge that you have read, understood, and agreed to these Terms and Conditions and the SpotOn ")}<PolicyLink />{t(". If you do not agree with these terms, please do not use the application.")}</Paragraph>
          <Paragraph>{t("SpotOn is a research prototype developed as part of an academic thesis project at De La Salle Lipa (DLSL). The application is intended for research, demonstration, and evaluation purposes.")}</Paragraph>
        </Section>

        <Section title={t("2. Important Medical Disclaimer")}>
          <SubHeading>{t("SpotOn Is Not a Medical Device")}</SubHeading>
          <WarningBanner>{t("SpotOn does not provide a medical diagnosis, medical advice, or medical treatment.")}</WarningBanner>
          <Paragraph>{t("SpotOn is an experimental research prototype that uses machine learning to analyze images and provide an estimated skin-lesion risk or urgency result. These results are intended solely to support research and demonstration of the technology.")}</Paragraph>
          <Paragraph>{t("SpotOn has not been reviewed, cleared, or approved by the Philippine Food and Drug Administration (FDA) as a medical device, and the application should not be considered a substitute for professional medical assessment.")}</Paragraph>
          <Paragraph>{t("The output generated by SpotOn may be incorrect. A result indicating lower risk does not mean that a lesion is harmless, while a result indicating higher risk does not mean that a lesion is cancerous.")}</Paragraph>

          <SubHeading>{t("Do Not Rely on SpotOn for Medical Decisions")}</SubHeading>
          <Paragraph>{t("You should not use SpotOn to:")}</Paragraph>
          <Bullet>{t("diagnose skin cancer or any other medical condition;")}</Bullet>
          <Bullet>{t("determine whether a lesion is malignant or benign;")}</Bullet>
          <Bullet>{t("decide whether medical treatment is necessary;")}</Bullet>
          <Bullet>{t("delay, cancel, or avoid a consultation with a healthcare professional; or")}</Bullet>
          <Bullet>{t("replace examination by a dermatologist or other qualified healthcare professional.")}</Bullet>
          <Paragraph>{t("If you notice a lesion that is changing, bleeding, painful, rapidly growing, unusually appearing, or otherwise concerning, seek evaluation from a qualified healthcare professional regardless of the result provided by SpotOn.")}</Paragraph>
        </Section>

        <Section title={t("3. Research Prototype")}>
          <Paragraph>{t("SpotOn is developed strictly for academic research and evaluation as part of a thesis project at De La Salle Lipa.")}</Paragraph>
          <Paragraph>{t("The machine learning models, algorithms, image-processing techniques, and risk assessments used by SpotOn are experimental. Their performance may vary depending on image quality, lighting conditions, skin characteristics, lesion characteristics, device hardware, and other factors.")}</Paragraph>
          <Paragraph>{t("The application has not been established as clinically valid for diagnosis or treatment.")}</Paragraph>
        </Section>

        <Section title={t("4. Eligibility")}>
          <Paragraph>{t("SpotOn is intended for individuals 18 years of age or older. By using SpotOn, you represent that you are at least 18 years old.")}</Paragraph>
          <Paragraph>{t("If you are unable to meet this requirement, do not create an account or use the application.")}</Paragraph>
        </Section>

        <Section title={t("5. User Responsibilities")}>
          <Paragraph>{t("You agree to:")}</Paragraph>
          <Bullet>{t("provide accurate information when creating an account;")}</Bullet>
          <Bullet>{t("use SpotOn only for lawful purposes and academic or research evaluation;")}</Bullet>
          <Bullet>{t("not intentionally upload content that belongs to another person without appropriate authorization;")}</Bullet>
          <Bullet>{t("not attempt to interfere with, compromise, or circumvent the application's security mechanisms;")}</Bullet>
          <Bullet>{t("not reverse engineer, decompile, modify, copy, or redistribute the application or its protected components without appropriate authorization; and")}</Bullet>
          <Bullet>{t("understand that SpotOn's results are experimental and must not be treated as medical diagnoses.")}</Bullet>
        </Section>

        <Section title={t("6. Information and Privacy")}>
          <Paragraph>{t("SpotOn collects and processes certain information necessary for account management, application functionality, research evaluation, and improvement of the prototype. Depending on the features you use, this may include:")}</Paragraph>
          <Bullet>{t("name;")}</Bullet>
          <Bullet>{t("email address;")}</Bullet>
          <Bullet>{t("telephone number;")}</Bullet>
          <Bullet>{t("date of birth;")}</Bullet>
          <Bullet>{t("sex;")}</Bullet>
          <Bullet>{t("Fitzpatrick skin type;")}</Bullet>
          <Bullet>{t("profile or avatar photograph;")}</Bullet>
          <Bullet>{t("skin-lesion photographs;")}</Bullet>
          <Bullet>{t("responses to skin-lesion or symptom-related questionnaires;")}</Bullet>
          <Bullet>{t("screening history and application-generated results;")}</Bullet>
          <Bullet>{t("consent-related information; and")}</Bullet>
          <Bullet>{t("location information when you use location-related features.")}</Bullet>
          <Paragraph>{t("Some of this information may constitute sensitive personal information or health-related information under applicable Philippine privacy laws.")}</Paragraph>
          <Paragraph>{t("Please refer to the SpotOn ")}<PolicyLink />{t(" for a detailed explanation of how information is collected, used, stored, protected, and deleted.")}</Paragraph>
        </Section>

        <Section title={t("7. On-Device Image Processing")}>
          <Paragraph>{t("Where supported by the current application implementation, skin-lesion image analysis is performed directly on your device.")}</Paragraph>
          <Paragraph>{t("Your lesion photographs and associated screening images are not routinely uploaded to SpotOn's application servers solely for machine-learning classification.")}</Paragraph>
          <Paragraph>{t("Images may remain within the application's private storage on your device while they are part of your screening history.")}</Paragraph>
          <Paragraph>{t("The specific handling of images may depend on the application version and features you use. The ")}<PolicyLink />{t(" provides further information regarding image storage and processing.")}</Paragraph>
        </Section>

        <Section title={t("8. Location Services")}>
          <Paragraph>{t("If you enable a location-dependent feature, SpotOn may access your device's location to provide location-related functionality, such as helping identify nearby dermatological clinics.")}</Paragraph>
          <Paragraph>{t("Location access is not required for the core image-classification functionality.")}</Paragraph>
          <Paragraph>{t("Third-party map or tile providers may receive information necessary to provide map functionality. Further information is provided in the")}{" "}
            <PolicyLink />.
          </Paragraph>
        </Section>

        <Section title={t("9. Research Use")}>
          <Paragraph>{t("Information collected through SpotOn may be used for academic research and evaluation associated with the thesis project, subject to applicable ethical and privacy requirements.")}</Paragraph>
          <Paragraph>{t("Research use does not mean that your personal information will be sold or used for advertising.")}</Paragraph>
          <Paragraph>{t("Where research analysis permits, information is de-identified or aggregated so that individual users are not unnecessarily identified.")}</Paragraph>
        </Section>

        <Section title={t("10. No Sale of Personal Information")}>
          <Paragraph>{t("SpotOn does not sell, rent, or trade users' personal information or uploaded photographs to advertisers or data brokers.")}</Paragraph>
          <Paragraph>{t("Third-party infrastructure and service providers may process limited information when necessary to operate the application. Such providers act as service providers or processors rather than as entities receiving your information for independent advertising purposes.")}</Paragraph>
        </Section>

        <Section title={t("11. Intellectual Property")}>
          <Paragraph>{t("Unless otherwise stated, the SpotOn application, user interface, source code, software architecture, machine-learning implementation, trained model components, original datasets or dataset compilations, documentation, and other original materials developed for the thesis are protected by applicable intellectual-property and academic policies.")}</Paragraph>
          <Paragraph>{t("Nothing in these Terms grants you ownership of SpotOn's intellectual property.")}</Paragraph>
          <Paragraph>
            <ThemedText
              type="subhead"
              themeColor="riskCritical"
              style={styles.inlineEmphasis}
            >{t("You may not reproduce, distribute, commercially exploit, reverse engineer, or create derivative works from protected components of SpotOn without appropriate authorization.")}</ThemedText></Paragraph>
        </Section>

        <Section title={t("12. Availability and Changes to the Service")}>
          <Paragraph>{t("SpotOn is an academic research prototype and may be modified, suspended, discontinued, or made unavailable at any time.")}</Paragraph>
          <Paragraph>{t("The thesis team may update application functionality as part of research, testing, maintenance, or academic requirements.")}</Paragraph>
          <Paragraph>{t("SpotOn does not guarantee uninterrupted availability or continued access to the application.")}</Paragraph>
        </Section>

        <Section title={t("13. Account Termination and Data Deletion")}>
          <Paragraph>{t("You may stop using SpotOn at any time.")}</Paragraph>
          <Paragraph>{t("Where account-deletion functionality is available, you may request deletion of your account and associated server-side personal information through the available application functionality or by contacting the project team.")}</Paragraph>
          <Paragraph>{t("Deleting the application from your device may remove locally stored screening information from the device, but uninstalling the application should not be treated as a request to delete server-side account information.")}</Paragraph>
          <Paragraph>{t("Requests concerning access, correction, or deletion of personal information may also be submitted using the contact information in the ")}<PolicyLink />.
          </Paragraph>
        </Section>

        <Section title={t("14. Limitation of Liability")}>
          <Paragraph>{t("SpotOn is provided on an “AS IS” and “AS AVAILABLE” basis for research and educational purposes.")}</Paragraph>
          <Paragraph>{t("To the extent permitted by applicable law, the thesis team and relevant project institution are not responsible for medical decisions, treatment delays, failure to seek medical care, or health outcomes arising from reliance on SpotOn's experimental output.")}</Paragraph>
          <Paragraph>{t("You acknowledge that machine-learning systems can produce inaccurate results, including false-positive and false-negative results.")}</Paragraph>
          <Paragraph>{t("Nothing in these Terms is intended to exclude liability that cannot legally be excluded under applicable law.")}</Paragraph>
        </Section>

        <Section title={t("15. Governing Law")}>
          <Paragraph>{t("These Terms shall be interpreted in accordance with applicable laws of the Republic of the Philippines.")}</Paragraph>
          <Paragraph>{t("Any dispute shall be subject to the applicable jurisdiction of Philippine courts, subject to mandatory laws and institutional policies.")}</Paragraph>
        </Section>

        <Section title={t("16. Changes to These Terms")}>
          <Paragraph>{t("SpotOn may update these Terms when the application's functionality, research procedures, privacy practices, or applicable requirements change.")}</Paragraph>
          <Paragraph>{t("The “Last Updated” date will be revised whenever material changes are made.")}</Paragraph>
          <Paragraph>{t("Where appropriate, users will be notified through the application or other reasonable means.")}</Paragraph>
        </Section>

        <Section title={t("17. Contact")}>
          <Paragraph>{t("For questions regarding these Terms, SpotOn, or the academic research project, contact the SpotOn Project Team:")}</Paragraph>
          <View style={styles.contactRow}>
            <ContactLink email={CONTACT_EMAIL} subject="SpotOn Terms and Conditions" />
          </View>
          <Paragraph>{t("For privacy-related concerns, requests, or complaints, please refer to the ")}<PolicyLink />.
          </Paragraph>
        </Section>

        <ThemedText
          type="footnote"
          themeColor="textSecondary"
          style={styles.closing}
        >{t("By continuing to use SpotOn after an updated version of these Terms becomes effective, you acknowledge the revised Terms.")}</ThemedText>
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  content: {
    paddingHorizontal: Space.xl,
    paddingTop: Space.base,
    paddingBottom: Space.xxl,
  },
  updated: {
    marginBottom: Space.sm,
  },
  section: {
    marginTop: Space.xxl,
    gap: Space.sm,
  },
  sectionTitle: {
    marginBottom: Space.xs,
  },
  subHeading: {
    fontWeight: "800",
    letterSpacing: 0.5,
    marginTop: Space.sm,
  },
  paragraph: {
    lineHeight: 21,
  },
  inlineEmphasis: {
    fontWeight: "700",
  },
  inlineLink: {
    fontWeight: "600",
  },
  warningBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Space.sm,
    borderWidth: 1,
    borderRadius: Radius.lg,
    padding: Space.base,
    marginBottom: Space.xs,
  },
  warningText: {
    flex: 1,
    fontWeight: "700",
    lineHeight: 20,
  },
  bulletRow: {
    flexDirection: "row",
    gap: Space.sm,
    paddingRight: Space.sm,
  },
  bulletDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    marginTop: 8,
    flexShrink: 0,
  },
  bulletText: {
    flex: 1,
    lineHeight: 21,
  },
  bulletLabel: {
    fontWeight: "700",
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: Space.xs,
  },
  closing: {
    marginTop: Space.xxl,
    lineHeight: 19,
  },
});
