import { ThemedText } from "@/components/themed-text";
import { DocumentHeader } from "@/components/ui/document-header";
import { Icon } from "@/components/ui/icon";
import { Screen } from "@/components/ui/screen";
import { ScrollView, StyleSheet, View } from "react-native";

import { Radius, Space } from "@/constants/theme";
import { useTheme } from "@/hooks/use-theme";

const LAST_UPDATED = "July 2026";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <View style={styles.section}>
      <ThemedText type="title2" style={styles.sectionTitle}>
        {title}
      </ThemedText>
      {children}
    </View>
  );
}

function Paragraph({ children }: { children: React.ReactNode }) {
  return (
    <ThemedText type="subhead" style={styles.paragraph}>
      {children}
    </ThemedText>
  );
}

function Bullet({
  label,
  children,
}: {
  label?: string;
  children: React.ReactNode;
}) {
  const theme = useTheme();
  return (
    <View style={styles.bulletRow}>
      <View style={[styles.bulletDot, { backgroundColor: theme.brand }]} />
      <ThemedText type="subhead" style={styles.bulletText}>
        {label ? (
          <ThemedText type="subhead" style={styles.bulletLabel}>
            {label}:{" "}
          </ThemedText>
        ) : null}
        {children}
      </ThemedText>
    </View>
  );
}

function WarningBanner({ children }: { children: React.ReactNode }) {
  const theme = useTheme();
  return (
    <View
      style={[
        styles.warningBanner,
        {
          backgroundColor: theme.riskCriticalBg,
          borderColor: theme.riskCritical,
        },
      ]}
    >
      <Icon
        name="exclamationmark.triangle.fill"
        tintColor={theme.riskCritical}
        size={20}
      />
      <ThemedText
        type="subhead"
        themeColor="riskCritical"
        style={styles.warningText}
      >
        {children}
      </ThemedText>
    </View>
  );
}

export default function TermsScreen() {
  return (
    <Screen padded={false}>
      <DocumentHeader title="Terms of Service" />

      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <ThemedText
          type="footnote"
          themeColor="textSecondary"
          style={styles.updated}
        >
          Last Updated: {LAST_UPDATED}
        </ThemedText>

        <Section title="1. Important Medical Disclaimer">
          <WarningBanner>
            This application is not a medical device and does not provide actual
            medical diagnoses or advice.
          </WarningBanner>

          <Bullet label="Research Prototype">
            This application is developed strictly as part of an academic thesis
            project at De La Salle Lipa. It has not been reviewed, cleared, or
            approved by the Food and Drug Administration (FDA).
          </Bullet>
          <Bullet label="No Clinical Validity">
            The machine learning model and image analysis algorithms used in
            this application are for experimental purposes only. Risk
            assessments generated by this application are highly speculative and
            should never substitute for a professional clinical evaluation.
          </Bullet>
          <Bullet label="Seek Professional Help">
            If you have a changing, bleeding, or otherwise concerning skin
            lesion, do not rely on this app. Immediately schedule an appointment
            with a board-certified dermatologist or qualified healthcare
            provider.
          </Bullet>
        </Section>

        <Section title="2. User Eligibility">
          <Paragraph>
            By using this application, you represent that you are at least 18
            years of age. This software is solely for demonstration and research
            evaluation purposes.
          </Paragraph>
        </Section>

        <Section title="3. Data Collection and Privacy">
          <Paragraph>
            As an academic project, data handling is governed by institutional
            ethics guidelines.
          </Paragraph>
          <Bullet label="Image Uploads">
            Any photographic images of skin lesions you upload are processed to
            determine an urgency level.
          </Bullet>
          <Bullet label="Secure Cloud Storage">
            Images and associated data are stored within a secured cloud and
            will not be sent or transferred anywhere other than the user&apos;s
            account.
          </Bullet>
          <Bullet label="No Commercialization">
            Your data will never be sold, shared with third-party advertisers,
            or used for commercial gain.
          </Bullet>
        </Section>

        <Section title={'4. Limitation of Liability and "As Is" Warranty'}>
          <Paragraph>
            This application is provided on an &quot;as is&quot; and &quot;as
            available&quot; basis, without warranties of any kind, either
            express or implied.
          </Paragraph>
          <Bullet>
            The thesis authors and De La Salle Lipa expressly disclaim any
            liability for any health outcomes, delayed medical treatments, or
            decisions made based on the output of the software.
          </Bullet>
          <Bullet>
            You use this software entirely at your own risk. The developers
            assume no responsibility for false positives (identifying a benign
            spot as high risk) or false negatives (identifying a malignant spot
            as low risk).
          </Bullet>
        </Section>

        <Section title="5. Intellectual Property">
          <Paragraph>
            The user interface, underlying code, dataset compilations, and
            trained machine learning model weights are the intellectual property
            of the thesis authors and De La Salle Lipa, protected under academic
            copyright laws. You may{" "}
            <ThemedText
              type="subhead"
              themeColor="riskCritical"
              style={styles.inlineEmphasis}
            >
              not reverse engineer, replicate, or redistribute
            </ThemedText>{" "}
            this software without explicit written permission.
          </Paragraph>
        </Section>

        <Section title="6. Termination of Service">
          <Paragraph>
            The thesis authors reserve the right to modify, suspend, or
            completely shut down this application at any time without prior
            notice, following the conclusion of the academic grading and defense
            process.
          </Paragraph>
        </Section>
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  content: {
    paddingHorizontal: Space.xl,
    paddingTop: Space.base,
    paddingBottom: Space.xxl,
  },
  updated: {
    marginBottom: Space.sm,
  },
  section: {
    marginTop: Space.xxl,
    gap: Space.sm,
  },
  sectionTitle: {
    marginBottom: Space.xs,
  },
  paragraph: {
    lineHeight: 21,
  },
  inlineEmphasis: {
    fontWeight: "700",
  },
  warningBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Space.sm,
    borderWidth: 1,
    borderRadius: Radius.lg,
    padding: Space.base,
    marginBottom: Space.xs,
  },
  warningText: {
    flex: 1,
    fontWeight: "700",
    lineHeight: 20,
  },
  bulletRow: {
    flexDirection: "row",
    gap: Space.sm,
    paddingRight: Space.sm,
  },
  bulletDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    marginTop: 8,
    flexShrink: 0,
  },
  bulletText: {
    flex: 1,
    lineHeight: 21,
  },
  bulletLabel: {
    fontWeight: "700",
  },
});
